### ISSUE TITLE
TryParse : Choice<T, string> like in Chiron

### ISSUE THREAD

**Issue by haf** [freya-fs/arachne#19]
I'm trying out a bit more of Arachne; how would you feel about moving to the same parsing result as in Chiron and Suave; `Choice<T, string>` which would allow you to feed parse errors to the callers? It would make for nicer code when integrating `Uri.TryParse`, for example.

**Comment by kolektiv** [comment]
Certainly worth considering - we'd need to do a bit of wrapping when used as prisms, as they're very much maybe types, but this could be useful in general.

**Comment by kolektiv** [comment]
Yes, agreed on this, Chiron does expose Choice types for tryParse functions, although it has an internal value/error type.

**Comment by kolektiv** [comment]
Fixed in #28 and should be available as part of Arachne 3.0.0-b083.
