### ISSUE TITLE
Naming in lower camel case?

### ISSUE THREAD

**Issue by haf** [freya-fs/arachne#20]
It would be nice as well, if the public functions were `lowerCamelCase` instead of upper, for the similarity with Chiron, Suave and so on.

**Comment by kolektiv** [comment]
Have you got some examples of this? I think that the uppercase functions that I know of are member functions, in which case upper is the convention, but i'm happy to admit I might be misremembering!

**Comment by haf** [comment]
Yes, the ones I think of are static member functions. I'm rationalising that since they are used in an equivalent manner to modules with ModuleSuffix functions, they should be named in an equivalent manner; there's no logical difference in how they're used. (I don't think this is a big deal, but wanted to raise the point none the less)

**Comment by kolektiv** [comment]
Yeah, I know what you mean. For me I'd prefer consistency, and I'm tempted to make an exception to these things which could also be implemented as module level functions. The different times when you end up with mixed cases have, I admit, annoyed me too. I think I'm going to try and make this change throughout Arachne and Freya (Freya is actually pretty much already there externally, as it's less common there) in time for the 3.0 releases of both.

**Comment by kolektiv** [comment]
Should be fixed in https://github.com/freya-fs/arachne/commit/5256497fcba6c65884738b20fdc2d7ffcdb9896b (and thus new pre-release...)
