### ISSUE TITLE
Fails to parse valid File URI

### ISSUE THREAD

**Issue by haf** [freya-fs/arachne#21]
https://en.wikipedia.org/wiki/File_URI_scheme

```
Uri.TryParse "file:///etc/fstab"
```

**Comment by kolektiv** [comment]
Hmmm. I'm not sure about this (and sorry, only just saw it!)

I'm not sure that's actually valid for Arachne.Uri - it implements RFC 3986 which I don't think would allow that either - I think. I think that would be considered obsolete?

**Comment by haf** [comment]
Why is it obsolete? How are you otherwise supposed to use absolute paths with URIs?

**Comment by kolektiv** [comment]
Hmmm. Actually yes, I think you're right now I'm more awake. Never read RFCs at 2am. I'll have a look at that, because I'm not sure why, given the design I remember of the URI parsers, that wouldn't work. Time for some more test coverage...

**Comment by kolektiv** [comment]
Fix is in https://github.com/kolektiv/arachne/commit/636ace59f555098461f4360a386b6e0cbf682174 for this, which seems to sort the problem. RegName was requiring a non-empty name, whereas an empty reg-name is valid according to the RFC (and should be interpreted by readers as localhost).

Cool, this one should be sorted!

**Comment by kolektiv** [comment]
Fixed in #28 and should be available as part of Arachne 3.0.0-b083.
