### ISSUE TITLE
Encoding as prisms

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/arachne#25]
Consider changing encoding and decoding of string values (escaped, etc.) to and from "friendly" forms with prisms, and maintaining the the basic "raw" form underneath, to support matching via uri template, query lenses, etc.

**Comment by kolektiv** [comment]
See #6 for one example, along with https://github.com/freya-fs/freya/issues/134 in Freya Router.

**Comment by panesofglass** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by kolektiv** [comment]
Values of percent-encoded strings within relevant types are now available through either a `raw_` or `decoded_` isomorphism when working with parts of data structures. By default percent-encoding and decoding is not done at parse/format time, and is only done through `decoded_` optic usage. This currently applies to the URI types, and changes have been made to reflect this in URI Templates also.

This was merged in and released in 3.0.0-b080.
