### ISSUE TITLE
Portable library support

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/arachne#26]
It should be possible to dual target net40 and profile259, given that only FParsec is a dependency.

**Comment by panesofglass** [comment]
:+1:

**Comment by kolektiv** [comment]
Should be fixed in https://github.com/freya-fs/arachne/commit/5256497fcba6c65884738b20fdc2d7ffcdb9896b but not closing until we've made a decision on xplat build, as that seems to be awkward, to say the least.

**Comment by kolektiv** [comment]
Closing after making the decision to temporarily halt x-plat builds as part of CI.
