### ISSUE TITLE
Move logic around matching/equality etc. from areas in Freya in to Arachne

### ISSUE THREAD

**Issue by kolektiv** [freya-fs/arachne#3]
For types such as language tags, which define specific matching semantics as part of specs, move the implementations of matching etc. in to Arachne (currently implementations exist in Freya, but they're not framework specific, and would be potentially useful to other users of the types in Arachne.

**Comment by kolektiv** [comment]
Make a decision on this for 3.0

**Comment by panesofglass** [comment]
:+1:

**Comment by kolektiv** [comment]
Relevant negotiation methods included in PR #35
