### ISSUE TITLE
Latest commits break Travis CI

### ISSUE THREAD

**Issue by panesofglass** [freya-fs/arachne#31]
Need to do the following:
- [x] Change the TargetFrameworkVersion for src and tests to 4.5 instead of 4.5.2
- [x] May want to consider backing TargetFSharpCoreVersion to 4.3.0.0 or 4.3.1.0
- [ ] Change FAKE build to MSBuild certain projects rather than Arachne.sln and disable PCL builds due to apparent lack of PCL profiles on Travis (?)

**Comment by kolektiv** [comment]
This is an interesting one. I guess we need to be sure what we're trying to solve by having a Travis build (what are we trying to validate?)

My thinking in terms of the changes to project targets was something like:
* Make the src projects as up to date as possible, so we know where we're not taking advantage of new features via compiler/lint warnings, etc. Make sure they validate that things work in the F# 4 world.
* Make each target the lowest it possibly can be. Deal with anomalies via #ifdef if needed.

What's the goal of shifting the src projects back to 4.5 and 4.3.0.0 or 4.3.1.0? We're never releasing those binaries. 4.5.2 is the only supported 4.5.x now too I believe?

Not unhappy to do it, just trying to work out the best way (Aether, Chiron, etc. have all taken this route too, but only have an AppVeyor build). What's our goal with Travis?

**Comment by panesofglass** [comment]
@forki I could use some help with Travis. Do you have any spare time to take a quick look?

**Comment by kolektiv** [comment]
I'm not sure we're going to get this nailed any time very soon, so I propose we move ahead without a proper Travis build (don't like doing it at all) and prioritize reinstating that ASAP once 3.0 is out. That's probably the pragmatic option unless there are strong objections?

**Comment by panesofglass** [comment]
@kolektiv, please do, and apologies for the delay. I'll see whether I can corner @ctaggart to help me with this soon.

**Comment by panesofglass** [comment]
@kolektiv, I spoke with @ctaggart who suggested we wait and focus on .NET Core instead. I think a happy medium might be to forget about travis-ci and any hope of building on a Mac/Linux for awhile. I think Xamarin Studio 6 may have better support for PCLs. We'll soon see.

**Comment by kolektiv** [comment]
Yes, I'm inclined to agree at this stage. It's rather out of our control for now, so I think we'll remove Travis integration (heavy hearts, etc...) and keep it on the backburner to revisit. I think Core will be a definite priority and we'll get support out for that as early as possible. I'm going to close this now and go ahead and remove Travis. I'm going to do the same with Freya too, as the same issue is going to apply as soon as multiple targets appear.

Thanks for trying! Sometimes things are just broken :smile:
