### ISSUE TITLE
QueryPairs fails when a parameter is incomplete

### ISSUE THREAD

**Issue by TWith2Sugars** [freya-fs/arachne#5]
If I try to parse the QueryPairs from "http://example.com?param1=exists&param=" I would expect a item list with [param1,Some test; param,None]

I've also included a pull request with a failing test to illustrate: https://github.com/freya-fs/arachne/pull/4

**Comment by TWith2Sugars** [comment]
So I think I've fixed it.

**Comment by TWith2Sugars** [comment]
Found another edge case that it fails on. Will attempt to fix it

**Comment by kolektiv** [comment]
So, this is interesting :) If you had that example above, would you expect the pair to be (param, None) or (param, Some "")?

Either way could work, but the presence of the equals sign to me implies that it is a pair, with the value being a zero length string. That probably requires a quick chance to pairPartP to change it requiring 1 or more chars for the value, to zero or more.

What do you reckon? :)

**Comment by TWith2Sugars** [comment]
Id vote for None, since there is not way to say Empty in a url and since the type is already string option I think people would already be expected to handle none cases :)

I'm also having difficulty handling when the '=' is missing - I've got a test I can push up but have no experience with FParsec to get it fixed.

**Comment by TWith2Sugars** [comment]
OR

if it has = then Some ""
if it doesn't then None

Thoughts?

**Comment by TWith2Sugars** [comment]
Also if the value is 0 length and it's made Some "", then at what query param would return None?

**Comment by TWith2Sugars** [comment]
So I've managed to handle another edge case - when '=' is missing the query pairs reports the correct result.

**Comment by TWith2Sugars** [comment]
This is done now that the pr is merged
